#!/usr/bin/env bash

ferrumDir=$(realpath $(dirname "$0")/..)

exportDir="${1:-exported-website}"

node \
  --stack-size=4000 \
  "$ferrumDir"/ts/gen/ferrum-org/ferrum-org.js \
  export-b $exportDir

