name: fe-in-fe
on: [push]


defaults:
  run:
    working-directory: ./run


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository 
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install modules
        run: ../cmds/install
      
      - name: Build
        run: ../cmds/build-ts

  test-fif-short-t:      
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test fif-short T
        run: ../cmds/runtest ../tests/fif-short.test.fe
        
  test-fif-short-g:      
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test fif-short G
        run: ../cmds/runtest -g=TD ../tests/fif-short.test.fe

  test-fif-medium-t:      
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test fif-medium T
        run: ../cmds/runtest ../tests/fif-medium.test.fe
        
  test-fif-long-t:      
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test fif-long T
        run: ../cmds/runtest ../tests/fif-long.test.fe
        
