name: fe-in-fe
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./run
    steps:
      - name: Check out the repository 
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install modules
        run: ../cmds/install
      
      - name: Build
        run: ../cmds/build-ts

      - name: Test fif-short T
        run: ../cmds/runtest ../tests/fif-short.test.fe
        
      - name: Test fif-short G
        run: ../cmds/runtest -g=TD ../tests/fif-short.test.fe

      - name: Test fif-medium T
        run: ../cmds/runtest ../tests/fif-medium.test.fe
        
      - name: Test fif-long T
        working-directory: ./run
        run: ../cmds/runtest ../tests/fif-long.test.fe
        
